### ISSUE TITLE
Getting error (zsh: segmentation fault)  on aws-runas on mac after upgrading to Sonoma

### ISSUE THREAD

**Issue by cdbrown100** [mmmorris1975/aws-runas#116]
I am getting the following error when I try to use aws-runas on a mac after upgrading to Sonoma.

**zsh: segmentation fault**

aws-runas-3.5.2-darwin-amd64.zip

Any ideas on this? Thank you.

**Comment by cdbrown100** [comment]
I downloaded 3.5.0 version and it worked.

**Comment by cdbrown100** [comment]
I downloaded 3.5.0 version and it worked.

**Comment by mmmorris1975** [comment]
Sorry I couldn't respond sooner.  This has been a long-standing issue with my Mac builds where the binaries generated during the CI build might exhibit this behavior.  (every other platform works fine)  The only workaround I've found so far is to recompile the release on Apple hardware and re-upload it.  For the 3.5.0 release, you might notice that the timestamps are different for the darwin executables, which is what happened there.

This is where the problem comes in ... I no longer have access to Apple hardware to directly test or recompile bad builds, so I can't find or fix the issue on my own.  If there's something you require from a later build, it may be best for you to download the golang toolchain and build locally (running `go build` should be sufficient for local use) if the executable from github is acting up
